title: "songbird"
description: "an engram's weekly observations"
baseurl: ""
url: "https://vngnc3.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "songbird"
  email: ""

github:
  username: vngnc3

show_downloads: false